name: AWS S3 Upload

on:
  push:
    branches: [main]
    paths:
      - 'level-4/**'
      - '.github/workflows/aws-s3-upload.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: level-4

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Upload to S3 Bucket
        run: |
          aws cp qna.txt s3://${{ secrets.S3_BUCKET}}
          
      - name: Verify upload
        run: |
         aws s3 ls s3://${{ secrets.S3_BUCKET}}/

      