name: Python Health Check

on: 
  push:
    branches: [ main ]
    paths:
      - 'python-health-checker/**'
      - '.github/workflows/ci.yaml'

jobs:
  health-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: python-health-checker

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Health Check
        run: python health_check.py
        env: 
          APP_ENV: production