name: Workflows, Jobs, and Steps

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-24.04
    steps: 
      - run: echo "Hi"
      - run: echo "I am"
      - run: echo "Jhon Wick"
      - run: echo "They call me BabaYaga!!!"
      - run: echo "Yeah!!!"
  job2:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Multiple jobs can run in parallel"
  job3:
    runs-on: ubuntu-24.04
    needs:
      - job1
      - job2
    steps:
      - run: echo "They can also depend on one another..."
  job4:
    runs-on: ubuntu-24.04
    needs:
      - job2
      - job3
    steps:
      - run: echo "...to form a directed acyclic graph (DAG)"