name: My First Workflow

on: 
  push:
    branches: [ main ]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check Python version
        run: python --version
      
      - name: Simulate Dependencies 
        run: echo "Installing dependencies..."

      - name: Simulate Tests
        run: echo "Running Python app..." 

      - name: Print Test
        run: python -c "print('Hello from Python')"
      
      - name: Print System Info
        run: uname -a
