name: Python Test Workflow

on:
  workflow_dispatch:

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check Python Version
        run: python --version

      - name: Run Test Script
        run: python -c "print('CI Working')"