name: Python Dependencies

on:
  push:
    paths: 
      - 'level-2/**' 

jobs:
  python-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: level-2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          echo "Success, all done"
