name: Log Analyzer CI

on:
  push:
    branches: [ main ]
    paths:
      - 'log-analyzer/**'
      - '.github/workflows/log-ci.yaml'
  workflow_dispatch:

jobs:
  analyze-logs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: log-analyzer

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Make script executable
        run: chmod +x run.sh

      - name: Run Pipeline
        run: ./run.sh
      