name: Python Practice CI

on:
  push:
    branches: [ main ]
    paths:
      - 'python-practice/**'
      - '.github/workflows/python-practice.yml'

jobs:
  run-python:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: python-practice

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Script 1
        run: python script1.py || echo "script1 failed" >> errors.log

      - name: Run Script 2
        run: python script2.py || echo "script2 failed" >> errors.log
        
      - name: Run Script 3
        run: python script3.py || echo "script3 failed" >> errors.log

      - name: Run Script with ENV
        run: python script4.py || echo "script4 failed" >> errors.log
        env:
          APP_ENV: production

      - name: Run Script 5
        run: python script5.py || echo "script5 failed" >> errors.log
        env:
          APP_ENV: production

      - name: Run Script 6
        working-directory: ./README.md
        run: python script6.py || echo "script6 failed" >> errors.log
      
      - name: Run Script 7
        run: python script7.py || echo "script7 failed" >> errors.log
        env:
          API_KEY: API7890
        
      - name: Run Script 8
        run: python script8.py || echo "script8 failed" >> errors.log
        env:
          API_KEY: API7890 
          APP_ENV: production

      - name: Final Check
        run: |
          if [ -f errors.log ]; then
            echo "Some scripts failed:"
            cat errors.log
            exit 1
          else
            echo "All scripts passed"
          fi
        

