name: Python CI Pipeline

on:
  push:
    paths: 
      - 'level-1/**'

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Test App Import
        run: python -c "import app"